# Generated by Django 5.0.3 on 2024-03-12 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_autor_editora_emprestimo_genero_livro_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='site',
        ),
        migrations.AddField(
            model_name='autor',
            name='Cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editora',
            name='Cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='editora',
            name='site',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='Livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.livro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='Usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='Autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.autor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livro',
            name='Genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.genero'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(),
        ),
    ]
